name: 04-Using Actions
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 0. Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4
      # 1. Setup node & Install deps of our react app
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Install Dependencies
        working-directory: 04-using-actions/react-app
        run: npm ci
      # 2. Execute automated tests
