name: 08-Using Variables
on:
  workflow_dispatch:

env:
  WORKFLOW_VAR: "Im a workflow var"
  OVERWRITTEN: "I will be overwritten"

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "Im a job env var"
      OVERWRITTEN: "I have been overwritten at job level"
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: "I am a step env var"
        run: |
          echo "Step env var: ${{ env.STEP_VAR }}"
          echo "Step job var: ${{ env.JOB_VAR }}"
          echo "Step workflow var: ${{ env.WORKFLOW_VAR }}"
          echo "Step overwritten var: ${{ env.OVERWRITTEN }}"
